version: '3.8'
services:
  explorer:
    build:
      context: ./snippets
      dockerfile: Dockerfile
    container_name: python_snippets
    volumes:
      - ./snippets/snippets:/app/snippets
      - ./snippets/poetry.lock:/app/poetry.lock
      - ./snippets/pyproject.toml:/app/pyproject.toml
