version: '3.8'
services:
  snippets:
    build:
      dockerfile: Dockerfile
    container_name: snippets
    volumes:
      - ./snippets:/app/snippets
      - ./poetry.lock:/app/poetry.lock
      - ./pyproject.toml:/app/pyproject.toml
      - ./server:/app/server
    ports:
        - 8000:8000
  postgres:
    image: postgres:15
    container_name: snippets_postgres
    environment:
        - POSTGRES_USER=snippets
        - POSTGRES_PASSWORD=snippets
        - POSTGRES_DB=snippets
    volumes:
        - postgres-data:/var/lib/postgresql/data
    ports:
        - 5432:5432
volumes:
  postgres-data:
